version: '3.8'
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '3000:3000'
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      PORT: 3000
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      AES_KEY: ${AES_KEY}
      ADMIN_LOGIN: ${ADMIN_LOGIN}
      ADMIN_PASS: ${ADMIN_PASS}
      DATABASE_URL: ${DATABASE_URL}

    networks:
      - app-network

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    command: [ "listen", "--forward-to", "http://localhost:3000/stripe/webhook", "--api-key", "${STRIPE_SECRET_KEY}" ]
    environment:
      STRIPE_API_KEY: ${STRIPE_SECRET_KEY}

    depends_on:
      - app
    network_mode: "host"
#
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '3001:80'  # Пробрасывает порт 80 контейнера на порт 3001 хоста
    environment:
      - REACT_APP_API_URL=http://app:3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge