export const USER_SERVICE_TOKEN = 'USER_SERVICE_TOKEN';

export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN';

export const JWT_SERVICE_TOKEN = 'JWT_SERVICE_TOKEN';

export const AUTH_SERVICE_TOKEN = 'AUTH_SERVICE_TOKEN';

export const PAYMENTS_SERVICE_TOKEN = 'PAYMENTS_SERVICE_TOKEN';
